# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/i18n/i18n.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/i18n/i18n.proto',
  package='erogen',
  syntax='proto3',
  serialized_options=_b('Z\004i18n'),
  serialized_pb=_b('\n\x15proto/i18n/i18n.proto\x12\x06\x65rogen\" \n\x12\x43ountryInfoRequest\x12\n\n\x02id\x18\x01 \x01(\r\";\n\x13\x43ountryInfoResponse\x12$\n\x07\x63ountry\x18\x01 \x01(\x0b\x32\x13.erogen.CountryInfo\"E\n\x14\x43ountriesInfoRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x03 \x01(\r\"E\n\x0b\x43ountryInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05iso_2\x18\x02 \x01(\t\x12\r\n\x05iso_3\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t2\xa7\x01\n\x0bI18nService\x12H\n\x0b\x43ountryInfo\x12\x1a.erogen.CountryInfoRequest\x1a\x1b.erogen.CountryInfoResponse\"\x00\x12N\n\rCountriesInfo\x12\x1c.erogen.CountriesInfoRequest\x1a\x1b.erogen.CountryInfoResponse\"\x00\x30\x01\x42\x06Z\x04i18nb\x06proto3')
)




_COUNTRYINFOREQUEST = _descriptor.Descriptor(
  name='CountryInfoRequest',
  full_name='erogen.CountryInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='erogen.CountryInfoRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=65,
)


_COUNTRYINFORESPONSE = _descriptor.Descriptor(
  name='CountryInfoResponse',
  full_name='erogen.CountryInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='erogen.CountryInfoResponse.country', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=126,
)


_COUNTRIESINFOREQUEST = _descriptor.Descriptor(
  name='CountriesInfoRequest',
  full_name='erogen.CountriesInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='erogen.CountriesInfoRequest.filter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='erogen.CountriesInfoRequest.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='erogen.CountriesInfoRequest.offset', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=197,
)


_COUNTRYINFO = _descriptor.Descriptor(
  name='CountryInfo',
  full_name='erogen.CountryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='erogen.CountryInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iso_2', full_name='erogen.CountryInfo.iso_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iso_3', full_name='erogen.CountryInfo.iso_3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='erogen.CountryInfo.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=268,
)

_COUNTRYINFORESPONSE.fields_by_name['country'].message_type = _COUNTRYINFO
DESCRIPTOR.message_types_by_name['CountryInfoRequest'] = _COUNTRYINFOREQUEST
DESCRIPTOR.message_types_by_name['CountryInfoResponse'] = _COUNTRYINFORESPONSE
DESCRIPTOR.message_types_by_name['CountriesInfoRequest'] = _COUNTRIESINFOREQUEST
DESCRIPTOR.message_types_by_name['CountryInfo'] = _COUNTRYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountryInfoRequest = _reflection.GeneratedProtocolMessageType('CountryInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _COUNTRYINFOREQUEST,
  __module__ = 'proto.i18n.i18n_pb2'
  # @@protoc_insertion_point(class_scope:erogen.CountryInfoRequest)
  ))
_sym_db.RegisterMessage(CountryInfoRequest)

CountryInfoResponse = _reflection.GeneratedProtocolMessageType('CountryInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _COUNTRYINFORESPONSE,
  __module__ = 'proto.i18n.i18n_pb2'
  # @@protoc_insertion_point(class_scope:erogen.CountryInfoResponse)
  ))
_sym_db.RegisterMessage(CountryInfoResponse)

CountriesInfoRequest = _reflection.GeneratedProtocolMessageType('CountriesInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _COUNTRIESINFOREQUEST,
  __module__ = 'proto.i18n.i18n_pb2'
  # @@protoc_insertion_point(class_scope:erogen.CountriesInfoRequest)
  ))
_sym_db.RegisterMessage(CountriesInfoRequest)

CountryInfo = _reflection.GeneratedProtocolMessageType('CountryInfo', (_message.Message,), dict(
  DESCRIPTOR = _COUNTRYINFO,
  __module__ = 'proto.i18n.i18n_pb2'
  # @@protoc_insertion_point(class_scope:erogen.CountryInfo)
  ))
_sym_db.RegisterMessage(CountryInfo)


DESCRIPTOR._options = None

_I18NSERVICE = _descriptor.ServiceDescriptor(
  name='I18nService',
  full_name='erogen.I18nService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=271,
  serialized_end=438,
  methods=[
  _descriptor.MethodDescriptor(
    name='CountryInfo',
    full_name='erogen.I18nService.CountryInfo',
    index=0,
    containing_service=None,
    input_type=_COUNTRYINFOREQUEST,
    output_type=_COUNTRYINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CountriesInfo',
    full_name='erogen.I18nService.CountriesInfo',
    index=1,
    containing_service=None,
    input_type=_COUNTRIESINFOREQUEST,
    output_type=_COUNTRYINFORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_I18NSERVICE)

DESCRIPTOR.services_by_name['I18nService'] = _I18NSERVICE

# @@protoc_insertion_point(module_scope)
