# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/i18n/i18n.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/i18n/i18n.proto", :syntax => :proto3) do
    add_message "erogen.CountryInfoRequest" do
      optional :id, :uint32, 1
    end
    add_message "erogen.CountryInfoResponse" do
      optional :country, :message, 1, "erogen.CountryInfo"
    end
    add_message "erogen.CountriesInfoRequest" do
      optional :filter, :string, 1
      optional :count, :uint32, 2
      optional :offset, :uint32, 3
    end
    add_message "erogen.CountryInfo" do
      optional :id, :uint32, 1
      optional :iso_2, :string, 2
      optional :iso_3, :string, 3
      optional :name, :string, 4
    end
  end
end

module Erogen
  CountryInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.CountryInfoRequest").msgclass
  CountryInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.CountryInfoResponse").msgclass
  CountriesInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.CountriesInfoRequest").msgclass
  CountryInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.CountryInfo").msgclass
end
