#!/bin/bash
#
# generates protocol buffers for definitions in proto/
#
#   (
#    cd "$ROOT_DIR" && \
#    protoc "$file_path" \
#      --cpp_out=. \
#      --go_out=plugins=grpc:. \
#      --js_out=library="$output_path":. \
#      --ruby_out=. \
#      --python_out=. \
#      --csharp_out="$base_path"
#  )

set -e

# ******************************************************************************
#    CONSTANTS

# script name
readonly SCRIPT_NAME="$(basename "$0")"
# root dir
readonly ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# scripts dir
readonly SCRIPT_DIR="$(cd "${ROOT_DIR}/.scripts" && pwd)"
# formatters
readonly FMT_VARS="$SCRIPT_DIR/_colors_"

# ******************************************************************************
#    MAIN FUNCS

# load formatters for logging
. "$FMT_VARS"

# script entrypoint.
main() {
  # ensure required binaries are installed
  check_required_binaries "protoc"

  log_info "Starting..."

  generate_proto_code "./proto/user" "./proto/user/user.proto" "./proto/user/user_pb"
  generate_proto_code "./proto/i18n" "./proto/i18n/i18n.proto" "./proto/i18n/i18n_pb"
  generate_proto_code "./proto/auth" "./proto/auth/auth.proto" "./proto/auth/auth.proto"

  log_info "Done!"
}

generate_proto_code() {
  local readonly base_path="$1"
  local readonly file_path="$2"
  local readonly output_path="$3"
  (
    cd "$ROOT_DIR" && \
    protoc "$file_path" \
      --go_out=plugins=grpc:.
  )
  
}

# ******************************************************************************
#    HELPER FUNCS


# check for required binaries
check_required_binaries() {
  local readonly bin_name="$1"

  if [[ ! $(command -v ${bin_name}) ]]; then
    log_error "Missing binary: '$bin_name' is required to run this script but is not in the system's PATH"
    exit 1
  fi
}


# ******************************************************************************
#    LOGGERS

# base logger
log() {
  local readonly lvl="$1"
  local readonly msg="$2"
  local readonly tst=$(date +"%H:%M:%S")
  printf "$FMT_CLR_PURPLE$tst $FMT_RESET$FMT_BOLD$lvl$FMT_RESET $msg\n"
}

# logger - LVL INFO
log_info() {
  log "\e[38;2;0;255;255m INFO [$SCRIPT_NAME]$FMT_RESET" "$1"
}

# logger - LVL WARN
log_warn() {
  log "\e[38;2;255;165;0m WARN [$SCRIPT_NAME]$FMT_RESET" "$1"
}

# logger - LVL ERROR
log_error() {
  log "\e[38;2;255;0;0mERROR [$SCRIPT_NAME]$FMT_RESET" "$1"
}

# ******************************************************************************
#    Execute

main "$@"
exit 0
