#!/bin/bash
#
# This script symlinks githooks in <root>/hooks/... to <root>/.git/hooks/...
#

set -e

# ******************************************************************************
#    CONSTANTS

# script name
readonly SCRIPT_NAME="$(basename "$0")"
# root dir
readonly ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# scripts dir
readonly SCRIPT_DIR="$(cd "${ROOT_DIR}/.scripts" && pwd)"
# formatters
readonly FMT_VARS="$SCRIPT_DIR/_colors_"

# ******************************************************************************
#    MAIN FUNCTIONS

# load formatters for logging
. "$FMT_VARS"

main() {
  log_info "Starting..."

  remove_existing_symlinks

  symlink_githooks

  log_info "Done!"
}

remove_existing_symlinks() {
  log_info "Removing existing symlinks..."
  find "${SCRIPT_DIR}/../.git/hooks" -type l -name '*' -exec rm {} +
}

symlink_githooks() {
  cd "${SCRIPT_DIR}/.."

  for filename in ${SCRIPT_DIR}/../.hooks/*; do
    filename=$(basename ${filename})

    log_info "${filename} setting access permissions"
    chmod +x "${SCRIPT_DIR}/../.hooks/${filename}"

    ln -s "../../.hooks/${filename}" ".git/hooks/${filename}"
    log_info "${filename} => .git/hooks/${filename} ✓"
  done
}

# ******************************************************************************
#    LOGGERS

# base logger
log() {
  local readonly lvl="$1"
  local readonly msg="$2"
  local readonly tst=$(date +"%H:%M:%S")
  printf "$FMT_CLR_PURPLE$tst $FMT_RESET$FMT_BOLD$lvl$FMT_RESET $msg\n"
}

# logger - LVL INFO
log_info() {
  log "\e[38;2;0;255;255m INFO [$SCRIPT_NAME]$FMT_RESET" "$1"
}

# logger - LVL WARN
log_warn() {
  log "\e[38;2;255;165;0m WARN [$SCRIPT_NAME]$FMT_RESET" "$1"
}

# logger - LVL ERROR
log_error() {
  log "\e[38;2;255;0;0mERROR [$SCRIPT_NAME]$FMT_RESET" "$1"
}

# ******************************************************************************
#    Execute

main "$@"
exit 0
