# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/user/user.proto", :syntax => :proto3) do
    add_message "erogen.LoginRequest" do
      optional :identifier, :string, 1
      optional :identifier_type, :enum, 2, "erogen.UserIdentifierType"
      optional :password, :string, 3
      optional :remember, :bool, 4
      optional :remember_for, :uint32, 5
      optional :fetch_tokens, :bool, 6
    end
    add_message "erogen.LoginResponse" do
      optional :success, :bool, 1
      optional :payload, :message, 2, "erogen.LoginResponse.TokenPayload"
    end
    add_message "erogen.LoginResponse.TokenPayload" do
      optional :id_token, :string, 1
      optional :access_token, :string, 2
      optional :refresh_token, :string, 3
      optional :token_type, :string, 4
      optional :scope, :string, 5
      optional :expires_in, :int32, 6
    end
    add_message "erogen.RegisterRequest" do
      optional :username, :string, 1
      optional :email_address, :string, 2
      optional :password, :string, 3
      optional :accepted_tos_version, :string, 4
    end
    add_message "erogen.RegisterResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
    end
    add_message "erogen.ChangeEmailRequest" do
      optional :id, :string, 1
      optional :current_email, :string, 2
      optional :new_email, :string, 3
    end
    add_message "erogen.ChangeEmailResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
    end
    add_message "erogen.ChangeUsernameRequest" do
      optional :id, :string, 1
      optional :current_username, :string, 2
      optional :new_username, :string, 3
    end
    add_message "erogen.ChangeUsernameResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
    end
    add_message "erogen.ChangePasswordRequest" do
      optional :id, :string, 1
      optional :current_password, :string, 2
      optional :new_password, :string, 3
    end
    add_message "erogen.ChangePasswordResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
    end
    add_message "erogen.ForgotPasswordRequest" do
      optional :email_address, :string, 1
    end
    add_message "erogen.ForgotPasswordResponse" do
      optional :user_exists, :bool, 1
      optional :sendemail_queued, :bool, 2
    end
    add_message "erogen.ResetPasswordRequest" do
      optional :user_id, :string, 1
      optional :new_password, :string, 2
    end
    add_message "erogen.ResetPasswordResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
    end
    add_message "erogen.ValidateTokenRequest" do
      optional :token, :string, 1
      optional :scope, :enum, 2, "erogen.ValidateTokenRequest.Scope"
    end
    add_enum "erogen.ValidateTokenRequest.Scope" do
      value :EMAIL_VERIFICATION, 0
      value :PASSWORD_RESET, 1
    end
    add_message "erogen.ValidateTokenResponse" do
      optional :success, :bool, 1
    end
    add_message "erogen.VerifySecurityQARequest" do
      optional :answer, :string, 1
    end
    add_message "erogen.VerifySecurityQAResponse" do
      optional :success, :bool, 1
    end
    add_message "erogen.UpdateRequest" do
      optional :user, :message, 1, "erogen.User"
    end
    add_message "erogen.UpdateResponse" do
      optional :success, :bool, 1
      optional :user, :message, 2, "erogen.User"
    end
    add_message "erogen.DeleteRequest" do
      optional :id, :string, 1
    end
    add_message "erogen.DeleteResponse" do
      optional :success, :bool, 1
    end
    add_message "erogen.UserRequest" do
      optional :id, :string, 1
    end
    add_message "erogen.UserResponse" do
      optional :user, :message, 1, "erogen.User"
    end
    add_message "erogen.UsersRequest" do
      optional :filter, :string, 1
      optional :count, :uint32, 2
      optional :offset, :uint32, 3
    end
    add_message "erogen.User" do
    end
    add_enum "erogen.UserIdentifierType" do
      value :UNKNOWN, 0
      value :USERNAME, 1
      value :EMAIL_ADDRESS, 2
      value :MOBILE_NUMBER, 3
    end
  end
end

module Erogen
  LoginRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.LoginRequest").msgclass
  LoginResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.LoginResponse").msgclass
  LoginResponse::TokenPayload = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.LoginResponse.TokenPayload").msgclass
  RegisterRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.RegisterRequest").msgclass
  RegisterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.RegisterResponse").msgclass
  ChangeEmailRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ChangeEmailRequest").msgclass
  ChangeEmailResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ChangeEmailResponse").msgclass
  ChangeUsernameRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ChangeUsernameRequest").msgclass
  ChangeUsernameResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ChangeUsernameResponse").msgclass
  ChangePasswordRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ChangePasswordRequest").msgclass
  ChangePasswordResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ChangePasswordResponse").msgclass
  ForgotPasswordRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ForgotPasswordRequest").msgclass
  ForgotPasswordResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ForgotPasswordResponse").msgclass
  ResetPasswordRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ResetPasswordRequest").msgclass
  ResetPasswordResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ResetPasswordResponse").msgclass
  ValidateTokenRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ValidateTokenRequest").msgclass
  ValidateTokenRequest::Scope = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ValidateTokenRequest.Scope").enummodule
  ValidateTokenResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.ValidateTokenResponse").msgclass
  VerifySecurityQARequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.VerifySecurityQARequest").msgclass
  VerifySecurityQAResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.VerifySecurityQAResponse").msgclass
  UpdateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.UpdateRequest").msgclass
  UpdateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.UpdateResponse").msgclass
  DeleteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.DeleteRequest").msgclass
  DeleteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.DeleteResponse").msgclass
  UserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.UserRequest").msgclass
  UserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.UserResponse").msgclass
  UsersRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.UsersRequest").msgclass
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.User").msgclass
  UserIdentifierType = Google::Protobuf::DescriptorPool.generated_pool.lookup("erogen.UserIdentifierType").enummodule
end
