// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserIdentifierType int32

const (
	UserIdentifierType_UNKNOWN       UserIdentifierType = 0
	UserIdentifierType_USERNAME      UserIdentifierType = 1
	UserIdentifierType_EMAIL_ADDRESS UserIdentifierType = 2
	UserIdentifierType_MOBILE_NUMBER UserIdentifierType = 3
)

var UserIdentifierType_name = map[int32]string{
	0: "UNKNOWN",
	1: "USERNAME",
	2: "EMAIL_ADDRESS",
	3: "MOBILE_NUMBER",
}
var UserIdentifierType_value = map[string]int32{
	"UNKNOWN":       0,
	"USERNAME":      1,
	"EMAIL_ADDRESS": 2,
	"MOBILE_NUMBER": 3,
}

func (x UserIdentifierType) String() string {
	return proto.EnumName(UserIdentifierType_name, int32(x))
}
func (UserIdentifierType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{0}
}

type ValidateTokenRequest_Scope int32

const (
	ValidateTokenRequest_EMAIL_VERIFICATION ValidateTokenRequest_Scope = 0
	ValidateTokenRequest_PASSWORD_RESET     ValidateTokenRequest_Scope = 1
)

var ValidateTokenRequest_Scope_name = map[int32]string{
	0: "EMAIL_VERIFICATION",
	1: "PASSWORD_RESET",
}
var ValidateTokenRequest_Scope_value = map[string]int32{
	"EMAIL_VERIFICATION": 0,
	"PASSWORD_RESET":     1,
}

func (x ValidateTokenRequest_Scope) String() string {
	return proto.EnumName(ValidateTokenRequest_Scope_name, int32(x))
}
func (ValidateTokenRequest_Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{14, 0}
}

type LoginRequest struct {
	Identifier           string             `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	IdentifierType       UserIdentifierType `protobuf:"varint,2,opt,name=identifier_type,json=identifierType,proto3,enum=erogen.UserIdentifierType" json:"identifier_type,omitempty"`
	Password             string             `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Remember             bool               `protobuf:"varint,4,opt,name=remember,proto3" json:"remember,omitempty"`
	RememberFor          uint32             `protobuf:"varint,5,opt,name=remember_for,json=rememberFor,proto3" json:"remember_for,omitempty"`
	FetchTokens          bool               `protobuf:"varint,6,opt,name=fetch_tokens,json=fetchTokens,proto3" json:"fetch_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *LoginRequest) GetIdentifierType() UserIdentifierType {
	if m != nil {
		return m.IdentifierType
	}
	return UserIdentifierType_UNKNOWN
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetRemember() bool {
	if m != nil {
		return m.Remember
	}
	return false
}

func (m *LoginRequest) GetRememberFor() uint32 {
	if m != nil {
		return m.RememberFor
	}
	return 0
}

func (m *LoginRequest) GetFetchTokens() bool {
	if m != nil {
		return m.FetchTokens
	}
	return false
}

type LoginResponse struct {
	Success              bool                        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Payload              *LoginResponse_TokenPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetPayload() *LoginResponse_TokenPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type LoginResponse_TokenPayload struct {
	IdToken              string   `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType            string   `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scope                string   `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	ExpiresIn            int32    `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse_TokenPayload) Reset()         { *m = LoginResponse_TokenPayload{} }
func (m *LoginResponse_TokenPayload) String() string { return proto.CompactTextString(m) }
func (*LoginResponse_TokenPayload) ProtoMessage()    {}
func (*LoginResponse_TokenPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{1, 0}
}
func (m *LoginResponse_TokenPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse_TokenPayload.Unmarshal(m, b)
}
func (m *LoginResponse_TokenPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse_TokenPayload.Marshal(b, m, deterministic)
}
func (dst *LoginResponse_TokenPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse_TokenPayload.Merge(dst, src)
}
func (m *LoginResponse_TokenPayload) XXX_Size() int {
	return xxx_messageInfo_LoginResponse_TokenPayload.Size(m)
}
func (m *LoginResponse_TokenPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse_TokenPayload.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse_TokenPayload proto.InternalMessageInfo

func (m *LoginResponse_TokenPayload) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

func (m *LoginResponse_TokenPayload) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse_TokenPayload) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginResponse_TokenPayload) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *LoginResponse_TokenPayload) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *LoginResponse_TokenPayload) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	EmailAddress         string   `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AcceptedTosVersion   string   `protobuf:"bytes,4,opt,name=accepted_tos_version,json=acceptedTosVersion,proto3" json:"accepted_tos_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetAcceptedTosVersion() string {
	if m != nil {
		return m.AcceptedTosVersion
	}
	return ""
}

type RegisterResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{3}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChangeEmailRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentEmail         string   `protobuf:"bytes,2,opt,name=current_email,json=currentEmail,proto3" json:"current_email,omitempty"`
	NewEmail             string   `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEmailRequest) Reset()         { *m = ChangeEmailRequest{} }
func (m *ChangeEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEmailRequest) ProtoMessage()    {}
func (*ChangeEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{4}
}
func (m *ChangeEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEmailRequest.Unmarshal(m, b)
}
func (m *ChangeEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEmailRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEmailRequest.Merge(dst, src)
}
func (m *ChangeEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEmailRequest.Size(m)
}
func (m *ChangeEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEmailRequest proto.InternalMessageInfo

func (m *ChangeEmailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeEmailRequest) GetCurrentEmail() string {
	if m != nil {
		return m.CurrentEmail
	}
	return ""
}

func (m *ChangeEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type ChangeEmailResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEmailResponse) Reset()         { *m = ChangeEmailResponse{} }
func (m *ChangeEmailResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeEmailResponse) ProtoMessage()    {}
func (*ChangeEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{5}
}
func (m *ChangeEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEmailResponse.Unmarshal(m, b)
}
func (m *ChangeEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEmailResponse.Marshal(b, m, deterministic)
}
func (dst *ChangeEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEmailResponse.Merge(dst, src)
}
func (m *ChangeEmailResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeEmailResponse.Size(m)
}
func (m *ChangeEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEmailResponse proto.InternalMessageInfo

func (m *ChangeEmailResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangeEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChangeUsernameRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentUsername      string   `protobuf:"bytes,2,opt,name=current_username,json=currentUsername,proto3" json:"current_username,omitempty"`
	NewUsername          string   `protobuf:"bytes,3,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeUsernameRequest) Reset()         { *m = ChangeUsernameRequest{} }
func (m *ChangeUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeUsernameRequest) ProtoMessage()    {}
func (*ChangeUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{6}
}
func (m *ChangeUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUsernameRequest.Unmarshal(m, b)
}
func (m *ChangeUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUsernameRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUsernameRequest.Merge(dst, src)
}
func (m *ChangeUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeUsernameRequest.Size(m)
}
func (m *ChangeUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUsernameRequest proto.InternalMessageInfo

func (m *ChangeUsernameRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeUsernameRequest) GetCurrentUsername() string {
	if m != nil {
		return m.CurrentUsername
	}
	return ""
}

func (m *ChangeUsernameRequest) GetNewUsername() string {
	if m != nil {
		return m.NewUsername
	}
	return ""
}

type ChangeUsernameResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeUsernameResponse) Reset()         { *m = ChangeUsernameResponse{} }
func (m *ChangeUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeUsernameResponse) ProtoMessage()    {}
func (*ChangeUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{7}
}
func (m *ChangeUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeUsernameResponse.Unmarshal(m, b)
}
func (m *ChangeUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeUsernameResponse.Marshal(b, m, deterministic)
}
func (dst *ChangeUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeUsernameResponse.Merge(dst, src)
}
func (m *ChangeUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeUsernameResponse.Size(m)
}
func (m *ChangeUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeUsernameResponse proto.InternalMessageInfo

func (m *ChangeUsernameResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangeUsernameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChangePasswordRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrentPassword      string   `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{8}
}
func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(dst, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{9}
}
func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(dst, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangePasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ForgotPasswordRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{10}
}
func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(dst, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type ForgotPasswordResponse struct {
	UserExists           bool     `protobuf:"varint,1,opt,name=user_exists,json=userExists,proto3" json:"user_exists,omitempty"`
	SendemailQueued      bool     `protobuf:"varint,2,opt,name=sendemail_queued,json=sendemailQueued,proto3" json:"sendemail_queued,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{11}
}
func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(dst, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

func (m *ForgotPasswordResponse) GetUserExists() bool {
	if m != nil {
		return m.UserExists
	}
	return false
}

func (m *ForgotPasswordResponse) GetSendemailQueued() bool {
	if m != nil {
		return m.SendemailQueued
	}
	return false
}

type ResetPasswordRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{12}
}
func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(dst, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{13}
}
func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(dst, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

func (m *ResetPasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResetPasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ValidateTokenRequest struct {
	Token                string                     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Scope                ValidateTokenRequest_Scope `protobuf:"varint,2,opt,name=scope,proto3,enum=erogen.ValidateTokenRequest_Scope" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ValidateTokenRequest) Reset()         { *m = ValidateTokenRequest{} }
func (m *ValidateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenRequest) ProtoMessage()    {}
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{14}
}
func (m *ValidateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenRequest.Unmarshal(m, b)
}
func (m *ValidateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenRequest.Marshal(b, m, deterministic)
}
func (dst *ValidateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenRequest.Merge(dst, src)
}
func (m *ValidateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenRequest.Size(m)
}
func (m *ValidateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenRequest proto.InternalMessageInfo

func (m *ValidateTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ValidateTokenRequest) GetScope() ValidateTokenRequest_Scope {
	if m != nil {
		return m.Scope
	}
	return ValidateTokenRequest_EMAIL_VERIFICATION
}

type ValidateTokenResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenResponse) Reset()         { *m = ValidateTokenResponse{} }
func (m *ValidateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResponse) ProtoMessage()    {}
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{15}
}
func (m *ValidateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResponse.Unmarshal(m, b)
}
func (m *ValidateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResponse.Marshal(b, m, deterministic)
}
func (dst *ValidateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResponse.Merge(dst, src)
}
func (m *ValidateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResponse.Size(m)
}
func (m *ValidateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResponse proto.InternalMessageInfo

func (m *ValidateTokenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type VerifySecurityQARequest struct {
	Answer               string   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySecurityQARequest) Reset()         { *m = VerifySecurityQARequest{} }
func (m *VerifySecurityQARequest) String() string { return proto.CompactTextString(m) }
func (*VerifySecurityQARequest) ProtoMessage()    {}
func (*VerifySecurityQARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{16}
}
func (m *VerifySecurityQARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySecurityQARequest.Unmarshal(m, b)
}
func (m *VerifySecurityQARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySecurityQARequest.Marshal(b, m, deterministic)
}
func (dst *VerifySecurityQARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySecurityQARequest.Merge(dst, src)
}
func (m *VerifySecurityQARequest) XXX_Size() int {
	return xxx_messageInfo_VerifySecurityQARequest.Size(m)
}
func (m *VerifySecurityQARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySecurityQARequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySecurityQARequest proto.InternalMessageInfo

func (m *VerifySecurityQARequest) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type VerifySecurityQAResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySecurityQAResponse) Reset()         { *m = VerifySecurityQAResponse{} }
func (m *VerifySecurityQAResponse) String() string { return proto.CompactTextString(m) }
func (*VerifySecurityQAResponse) ProtoMessage()    {}
func (*VerifySecurityQAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{17}
}
func (m *VerifySecurityQAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySecurityQAResponse.Unmarshal(m, b)
}
func (m *VerifySecurityQAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySecurityQAResponse.Marshal(b, m, deterministic)
}
func (dst *VerifySecurityQAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySecurityQAResponse.Merge(dst, src)
}
func (m *VerifySecurityQAResponse) XXX_Size() int {
	return xxx_messageInfo_VerifySecurityQAResponse.Size(m)
}
func (m *VerifySecurityQAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySecurityQAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySecurityQAResponse proto.InternalMessageInfo

func (m *VerifySecurityQAResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{18}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{19}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{20}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{21}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{22}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (dst *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(dst, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{23}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UsersRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{24}
}
func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (dst *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(dst, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *UsersRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UsersRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type User struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_dfa8013309085ae9, []int{25}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "erogen.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "erogen.LoginResponse")
	proto.RegisterType((*LoginResponse_TokenPayload)(nil), "erogen.LoginResponse.TokenPayload")
	proto.RegisterType((*RegisterRequest)(nil), "erogen.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "erogen.RegisterResponse")
	proto.RegisterType((*ChangeEmailRequest)(nil), "erogen.ChangeEmailRequest")
	proto.RegisterType((*ChangeEmailResponse)(nil), "erogen.ChangeEmailResponse")
	proto.RegisterType((*ChangeUsernameRequest)(nil), "erogen.ChangeUsernameRequest")
	proto.RegisterType((*ChangeUsernameResponse)(nil), "erogen.ChangeUsernameResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "erogen.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "erogen.ChangePasswordResponse")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "erogen.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "erogen.ForgotPasswordResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "erogen.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "erogen.ResetPasswordResponse")
	proto.RegisterType((*ValidateTokenRequest)(nil), "erogen.ValidateTokenRequest")
	proto.RegisterType((*ValidateTokenResponse)(nil), "erogen.ValidateTokenResponse")
	proto.RegisterType((*VerifySecurityQARequest)(nil), "erogen.VerifySecurityQARequest")
	proto.RegisterType((*VerifySecurityQAResponse)(nil), "erogen.VerifySecurityQAResponse")
	proto.RegisterType((*UpdateRequest)(nil), "erogen.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "erogen.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "erogen.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "erogen.DeleteResponse")
	proto.RegisterType((*UserRequest)(nil), "erogen.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "erogen.UserResponse")
	proto.RegisterType((*UsersRequest)(nil), "erogen.UsersRequest")
	proto.RegisterType((*User)(nil), "erogen.User")
	proto.RegisterEnum("erogen.UserIdentifierType", UserIdentifierType_name, UserIdentifierType_value)
	proto.RegisterEnum("erogen.ValidateTokenRequest_Scope", ValidateTokenRequest_Scope_name, ValidateTokenRequest_Scope_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// unauthenticated requests
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// authenticated write requests
	ChangeEmail(ctx context.Context, in *ChangeEmailRequest, opts ...grpc.CallOption) (*ChangeEmailResponse, error)
	ChangeUsername(ctx context.Context, in *ChangeUsernameRequest, opts ...grpc.CallOption) (*ChangeUsernameResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	VerifySecurityQA(ctx context.Context, in *VerifySecurityQARequest, opts ...grpc.CallOption) (*VerifySecurityQAResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// authenticated read requests
	User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (UserService_UsersClient, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangeEmail(ctx context.Context, in *ChangeEmailRequest, opts ...grpc.CallOption) (*ChangeEmailResponse, error) {
	out := new(ChangeEmailResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/ChangeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangeUsername(ctx context.Context, in *ChangeUsernameRequest, opts ...grpc.CallOption) (*ChangeUsernameResponse, error) {
	out := new(ChangeUsernameResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/ChangeUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifySecurityQA(ctx context.Context, in *VerifySecurityQARequest, opts ...grpc.CallOption) (*VerifySecurityQAResponse, error) {
	out := new(VerifySecurityQAResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/VerifySecurityQA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/erogen.UserService/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (UserService_UsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[0], "/erogen.UserService/Users", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_UsersClient interface {
	Recv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceUsersClient) Recv() (*UserResponse, error) {
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// unauthenticated requests
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// authenticated write requests
	ChangeEmail(context.Context, *ChangeEmailRequest) (*ChangeEmailResponse, error)
	ChangeUsername(context.Context, *ChangeUsernameRequest) (*ChangeUsernameResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	VerifySecurityQA(context.Context, *VerifySecurityQARequest) (*VerifySecurityQAResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*UpdateResponse, error)
	// authenticated read requests
	User(context.Context, *UserRequest) (*UserResponse, error)
	Users(*UsersRequest, UserService_UsersServer) error
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/ChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangeEmail(ctx, req.(*ChangeEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangeUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangeUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/ChangeUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangeUsername(ctx, req.(*ChangeUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifySecurityQA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySecurityQARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifySecurityQA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/VerifySecurityQA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifySecurityQA(ctx, req.(*VerifySecurityQARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/erogen.UserService/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Users_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).Users(m, &userServiceUsersServer{stream})
}

type UserService_UsersServer interface {
	Send(*UserResponse) error
	grpc.ServerStream
}

type userServiceUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceUsersServer) Send(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "erogen.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _UserService_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _UserService_ValidateToken_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _UserService_ChangeEmail_Handler,
		},
		{
			MethodName: "ChangeUsername",
			Handler:    _UserService_ChangeUsername_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserService_ChangePassword_Handler,
		},
		{
			MethodName: "VerifySecurityQA",
			Handler:    _UserService_VerifySecurityQA_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
		{
			MethodName: "User",
			Handler:    _UserService_User_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Users",
			Handler:       _UserService_Users_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/user/user.proto",
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_user_dfa8013309085ae9) }

var fileDescriptor_user_dfa8013309085ae9 = []byte{
	// 1173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x4f, 0x1b, 0x47,
	0x14, 0xce, 0x3a, 0xf8, 0xc2, 0xf1, 0x05, 0x77, 0x62, 0x83, 0xeb, 0x94, 0xe0, 0x6e, 0x5f, 0x68,
	0x1e, 0x28, 0x81, 0xaa, 0x17, 0x29, 0x52, 0x65, 0xc0, 0xa8, 0x56, 0xc0, 0xc0, 0xd8, 0x06, 0xa9,
	0x2f, 0xd6, 0xc6, 0x7b, 0xec, 0xac, 0x0a, 0xbb, 0xce, 0xce, 0x3a, 0x84, 0xdf, 0xd2, 0x97, 0x3e,
	0xf5, 0xb5, 0xbf, 0xa2, 0x3f, 0xa8, 0xff, 0xa0, 0x9a, 0xdb, 0xda, 0xeb, 0x5d, 0xc7, 0x91, 0xe8,
	0x0b, 0xe2, 0xdc, 0xbe, 0x39, 0xdf, 0x99, 0xd9, 0x6f, 0xc6, 0x50, 0x9d, 0xf8, 0x5e, 0xe0, 0x7d,
	0x37, 0x65, 0xe8, 0x8b, 0x3f, 0x7b, 0xc2, 0x26, 0x19, 0xf4, 0xbd, 0x31, 0xba, 0xe6, 0xbf, 0x06,
	0x14, 0xce, 0xbc, 0xb1, 0xe3, 0x52, 0x7c, 0x3f, 0x45, 0x16, 0x90, 0x17, 0x00, 0x8e, 0x8d, 0x6e,
	0xe0, 0x8c, 0x1c, 0xf4, 0x6b, 0x46, 0xc3, 0xd8, 0x5d, 0xa7, 0x73, 0x1e, 0x72, 0x0c, 0x1b, 0x33,
	0x6b, 0x10, 0x3c, 0x4c, 0xb0, 0x96, 0x6a, 0x18, 0xbb, 0xa5, 0x83, 0xfa, 0x9e, 0x84, 0xdc, 0xeb,
	0x33, 0xf4, 0xdb, 0x61, 0x4a, 0xef, 0x61, 0x82, 0xb4, 0xe4, 0x44, 0x6c, 0x52, 0x87, 0xdc, 0xc4,
	0x62, 0xec, 0xde, 0xf3, 0xed, 0xda, 0x53, 0xb1, 0x44, 0x68, 0xf3, 0x98, 0x8f, 0x77, 0x78, 0xf7,
	0x16, 0xfd, 0xda, 0x5a, 0xc3, 0xd8, 0xcd, 0xd1, 0xd0, 0x26, 0x5f, 0x43, 0x41, 0xff, 0x3f, 0x18,
	0x79, 0x7e, 0x2d, 0xdd, 0x30, 0x76, 0x8b, 0x34, 0xaf, 0x7d, 0xa7, 0x9e, 0x48, 0x19, 0x61, 0x30,
	0x7c, 0x37, 0x08, 0xbc, 0xdf, 0xd1, 0x65, 0xb5, 0x8c, 0x80, 0xc8, 0x0b, 0x5f, 0x4f, 0xb8, 0xcc,
	0xbf, 0x53, 0x50, 0x54, 0x9c, 0xd9, 0xc4, 0x73, 0x19, 0x92, 0x1a, 0x64, 0xd9, 0x74, 0x38, 0x44,
	0xc6, 0x04, 0xe3, 0x1c, 0xd5, 0x26, 0x79, 0x0d, 0xd9, 0x89, 0xf5, 0x70, 0xeb, 0x59, 0xb6, 0xa0,
	0x99, 0x3f, 0x30, 0x35, 0xcd, 0x08, 0xc2, 0x9e, 0x80, 0xbe, 0x94, 0x99, 0x54, 0x97, 0xd4, 0xff,
	0x31, 0xa0, 0x30, 0x1f, 0x21, 0x5f, 0x42, 0xce, 0xb1, 0x65, 0x6b, 0x6a, 0xb6, 0x59, 0xc7, 0x16,
	0x19, 0xbc, 0x71, 0x4b, 0xac, 0xa9, 0xc2, 0x29, 0x11, 0xce, 0x4b, 0x9f, 0x4c, 0xf9, 0x06, 0x8a,
	0x3e, 0x8e, 0x7c, 0x64, 0x8a, 0x9d, 0x9a, 0x5d, 0x41, 0x39, 0x65, 0xd2, 0x36, 0x80, 0x08, 0xca,
	0xbd, 0x59, 0x13, 0x19, 0xeb, 0xc2, 0x23, 0x46, 0x5f, 0x81, 0x34, 0x1b, 0x7a, 0x13, 0x14, 0xb3,
	0x5b, 0xa7, 0xd2, 0xe0, 0x45, 0xf8, 0x71, 0xe2, 0xf8, 0xc8, 0x06, 0x8e, 0x2b, 0x66, 0x96, 0xa6,
	0xeb, 0xca, 0xd3, 0x76, 0xcd, 0x3f, 0x0d, 0xd8, 0xa0, 0x38, 0x76, 0x58, 0x80, 0xbe, 0x3e, 0x28,
	0x75, 0xc8, 0xf1, 0xf3, 0xe4, 0x5a, 0x77, 0xa8, 0xa8, 0x84, 0x36, 0x6f, 0x14, 0xef, 0x2c, 0xe7,
	0x76, 0x60, 0xd9, 0xb6, 0xcf, 0xa7, 0x2a, 0xc9, 0x14, 0x84, 0xb3, 0x29, 0x7d, 0x9f, 0x3c, 0x04,
	0xfb, 0x50, 0xe1, 0xc4, 0x27, 0x01, 0xf2, 0x69, 0xb1, 0xc1, 0x07, 0xf4, 0x99, 0xe3, 0xb9, 0x8a,
	0x0e, 0xd1, 0xb1, 0x9e, 0xc7, 0xae, 0x65, 0xc4, 0x3c, 0x85, 0xf2, 0xac, 0xc3, 0x95, 0xdb, 0x5a,
	0x83, 0xec, 0x1d, 0x32, 0x66, 0x8d, 0x51, 0xb5, 0xa6, 0x4d, 0x73, 0x04, 0xe4, 0xf8, 0x9d, 0xe5,
	0x8e, 0xb1, 0xc5, 0x7b, 0xd5, 0x64, 0x4b, 0x90, 0x72, 0x6c, 0x45, 0x33, 0xe5, 0xd8, 0x9c, 0xe0,
	0x70, 0xea, 0xfb, 0xe8, 0x06, 0x03, 0xc1, 0x49, 0x13, 0x54, 0x4e, 0x51, 0x4b, 0x9e, 0xc3, 0xba,
	0x8b, 0xf7, 0x2a, 0x41, 0x31, 0x74, 0xf1, 0x5e, 0x04, 0xcd, 0x36, 0x3c, 0x8b, 0xac, 0xf3, 0x88,
	0x96, 0xa7, 0x50, 0x95, 0x50, 0x7d, 0x35, 0xff, 0x65, 0x5d, 0x7f, 0x0b, 0x65, 0xdd, 0x75, 0xb8,
	0x75, 0x12, 0x6b, 0x43, 0xf9, 0x35, 0x02, 0x3f, 0x8d, 0xbc, 0xf7, 0x30, 0x4d, 0xb6, 0x9f, 0x77,
	0xf1, 0x5e, 0xa7, 0x98, 0x67, 0xb0, 0xb9, 0xb8, 0xec, 0xff, 0x41, 0xe2, 0x52, 0x9d, 0x81, 0xcf,
	0x20, 0x11, 0x1e, 0x9f, 0x28, 0x09, 0x8d, 0xa0, 0x49, 0x2c, 0x9c, 0x32, 0x4e, 0x42, 0xa7, 0xcc,
	0x48, 0xcc, 0x96, 0x7d, 0x04, 0x89, 0xd7, 0x50, 0x3d, 0xf5, 0xfc, 0xb1, 0x17, 0x2c, 0x92, 0x88,
	0x7d, 0x10, 0x46, 0xfc, 0x83, 0x30, 0x6d, 0xd8, 0x5c, 0xac, 0x56, 0xbd, 0xec, 0x40, 0x9e, 0xef,
	0xc4, 0x00, 0x3f, 0x3a, 0x2c, 0xd0, 0xfd, 0x00, 0x77, 0xb5, 0x84, 0x87, 0x0f, 0x85, 0xa1, 0x6b,
	0xcb, 0x35, 0xde, 0x4f, 0x71, 0x8a, 0x72, 0x28, 0x39, 0xba, 0x11, 0xfa, 0xaf, 0x84, 0xdb, 0xa4,
	0x50, 0xa1, 0xc8, 0x30, 0xd6, 0xe2, 0x16, 0x64, 0xc5, 0x1a, 0xe1, 0xb0, 0x33, 0x53, 0x21, 0xe4,
	0xb1, 0x29, 0xa6, 0xe2, 0x53, 0x7c, 0x03, 0xd5, 0x05, 0xcc, 0x47, 0x0c, 0xf1, 0x0f, 0x03, 0x2a,
	0xd7, 0xd6, 0xad, 0x63, 0x5b, 0x01, 0x0a, 0x49, 0xd3, 0x1d, 0x56, 0x20, 0x3d, 0xaf, 0x9c, 0xd2,
	0x20, 0x3f, 0x69, 0x41, 0x93, 0xd7, 0x50, 0xa8, 0xcf, 0x49, 0x10, 0x7b, 0x5d, 0x9e, 0xa9, 0x44,
	0xcf, 0x3c, 0x84, 0xb4, 0xb0, 0xc9, 0x26, 0x90, 0xd6, 0x79, 0xb3, 0x7d, 0x36, 0xb8, 0x6e, 0xd1,
	0xf6, 0x69, 0xfb, 0xb8, 0xd9, 0x6b, 0x5f, 0x74, 0xca, 0x4f, 0x08, 0x81, 0xd2, 0x65, 0xb3, 0xdb,
	0xbd, 0xb9, 0xa0, 0x27, 0x03, 0xda, 0xea, 0xb6, 0x7a, 0x65, 0xc3, 0x7c, 0x05, 0xd5, 0x05, 0xe4,
	0x55, 0x54, 0xcd, 0x57, 0xb0, 0x75, 0x8d, 0xbe, 0x33, 0x7a, 0xe8, 0xe2, 0x70, 0xea, 0x3b, 0xc1,
	0xc3, 0x55, 0x53, 0x53, 0xda, 0x84, 0x8c, 0xe5, 0xb2, 0xfb, 0xf0, 0xa6, 0x55, 0x96, 0xf9, 0x3d,
	0xd4, 0xe2, 0x25, 0x9f, 0xb1, 0x50, 0xb1, 0x3f, 0xe1, 0x9d, 0x69, 0xf8, 0x06, 0xac, 0xf1, 0x4d,
	0x14, 0x79, 0xf9, 0x83, 0xc2, 0xfc, 0x0d, 0x4d, 0x45, 0xc4, 0x3c, 0x83, 0x92, 0x2e, 0x59, 0xb9,
	0x65, 0x1a, 0x2d, 0xb5, 0x14, 0x6d, 0x07, 0x8a, 0x27, 0x78, 0x8b, 0xc1, 0x32, 0x05, 0x32, 0x5f,
	0x42, 0x49, 0x27, 0xac, 0x64, 0xb3, 0x0d, 0x79, 0x01, 0xbd, 0x04, 0x6a, 0x1f, 0x0a, 0x32, 0xac,
	0x80, 0x56, 0x73, 0xed, 0xc9, 0x0a, 0x36, 0x37, 0xfc, 0x91, 0x73, 0x1b, 0xcc, 0x86, 0x2f, 0x2d,
	0x7e, 0xce, 0x86, 0xde, 0xd4, 0x0d, 0x04, 0xd1, 0x22, 0x95, 0x06, 0xcf, 0xf6, 0x46, 0x23, 0x86,
	0x81, 0x90, 0x91, 0x22, 0x55, 0x96, 0x99, 0x81, 0x35, 0x8e, 0xfa, 0xb2, 0x0f, 0x24, 0xfe, 0xf2,
	0x21, 0x79, 0xc8, 0xf6, 0x3b, 0x6f, 0x3a, 0x17, 0x37, 0xfc, 0x3c, 0x15, 0x20, 0xd7, 0xef, 0xb6,
	0x68, 0xa7, 0x79, 0xde, 0x2a, 0x1b, 0xe4, 0x0b, 0x28, 0xca, 0x53, 0xd7, 0x3c, 0x39, 0xa1, 0xad,
	0x6e, 0xb7, 0x9c, 0xe2, 0xae, 0xf3, 0x8b, 0xa3, 0xf6, 0x59, 0x6b, 0xd0, 0xe9, 0x9f, 0x1f, 0xb5,
	0x68, 0xf9, 0xe9, 0xc1, 0x5f, 0x59, 0x39, 0x86, 0x2e, 0xfa, 0x1f, 0x9c, 0x21, 0x92, 0x1f, 0x20,
	0x2d, 0x5e, 0x1e, 0xa4, 0xb2, 0xf0, 0x10, 0x11, 0x9c, 0xea, 0xd5, 0xc4, 0xe7, 0x89, 0xf9, 0x84,
	0xfc, 0x02, 0x39, 0x7d, 0x3f, 0x92, 0x2d, 0x9d, 0xb4, 0x70, 0xa7, 0xd7, 0x6b, 0xf1, 0x40, 0x08,
	0x70, 0x05, 0xa5, 0xa8, 0x3a, 0x91, 0x6d, 0x9d, 0x9d, 0xa8, 0x79, 0xf5, 0x17, 0xcb, 0xc2, 0x21,
	0x64, 0x07, 0x8a, 0x11, 0xd9, 0x20, 0x5f, 0xcd, 0xd6, 0x8f, 0x2b, 0x54, 0x7d, 0x7b, 0x49, 0x74,
	0x1e, 0x2f, 0xf2, 0x6d, 0xce, 0xf0, 0x92, 0xc4, 0x60, 0x86, 0x97, 0xf8, 0x41, 0x9b, 0x4f, 0xc8,
	0xaf, 0x90, 0x9f, 0xbb, 0xa3, 0x49, 0xf8, 0xc2, 0x8d, 0x3f, 0x10, 0xea, 0xcf, 0x13, 0x63, 0xf3,
	0xc3, 0x8b, 0xde, 0x95, 0xb3, 0xe1, 0x25, 0x5e, 0xdd, 0xb3, 0xe1, 0x25, 0x5f, 0xb1, 0xf3, 0x90,
	0xf1, 0xfd, 0x48, 0xbc, 0x48, 0x17, 0x21, 0x13, 0xe6, 0x77, 0x03, 0xe5, 0x45, 0xd5, 0x21, 0x3b,
	0xe1, 0x90, 0x92, 0x25, 0xac, 0xde, 0x58, 0x9e, 0x10, 0x02, 0xff, 0x0c, 0x19, 0xa9, 0x32, 0x24,
	0x3c, 0x9f, 0x11, 0xa1, 0xaa, 0x6f, 0x2e, 0xba, 0xe7, 0x4b, 0xa5, 0x62, 0xcc, 0x4a, 0x23, 0x12,
	0xf3, 0x89, 0xd2, 0x43, 0xf9, 0x65, 0x92, 0x67, 0x11, 0x2d, 0x50, 0x65, 0x95, 0xa8, 0x33, 0x2c,
	0xfa, 0x11, 0xd2, 0x42, 0x24, 0x48, 0x24, 0x81, 0xad, 0x28, 0xdb, 0x37, 0x8e, 0x32, 0xbf, 0x09,
	0x95, 0x79, 0x9b, 0x11, 0x3f, 0xb0, 0x0e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x66, 0xee, 0xfb,
	0x46, 0x79, 0x0d, 0x00, 0x00,
}
